version: "2.2"
services:
  postgres:
    image: "postgres:latest"
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: croissant_dev
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
volumes:
  data01:
    driver: local
